# Generated by Django 4.1.13 on 2024-07-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedModel',
        ),
    ]
