# Generated by Django 4.1.13 on 2024-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='select_time',
            field=models.CharField(max_length=100),
        ),
    ]
